# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2bf6e7cf15bccb2a4dcad424071f45119ece00ebde56b73d63c49779b13990ee6549c7da09f1efcef5acdb2729cf9a2f8dea75223b583bd7857125a05336138

test:
  secret_key_base: cdba9a373660a53219a6270dc2d11f0978a8c3381f1e7f02315c0e248dc3d9703081837ca4d2cdb00e095ae7ecaf983b8787b33b5250625e3862caf91c86becc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
